
ALTER TABLE customer
RENAME COLUMN id to IDT_ID;

ALTER TABLE customer
RENAME COLUMN cpf_cnpj TO IDT_CPF_CNPJ;

ALTER TABLE customer
RENAME COLUMN nome TO NAM_CUSTOMER_NAME;

ALTER TABLE customer
RENAME COLUMN address TO IDT_CUSTOMER_ADDRESS;

ALTER TABLE customer
RENAME COLUMN phone TO IDT_CUSTOMER_PHONE;

ALTER TABLE customer
RENAME COLUMN email TO IDT_CUSTOMER_EMAIL;
